"""Template text for the practice report (F-08). Every sentence is filled from measured numbers
in the report data; nothing is generated by a language model (LLM wording is Phase 7).

Tier words: "strong" = beyond the experts' 99th percentile ("well outside the expert range"),
"notable" = beyond the 95th ("outside the usual expert range"). DECISIONS 2026-09-28.
"""

from __future__ import annotations

import math
from typing import Any

import numpy as np

from pianolens.report import calibration as cal

TIER_WORDS = {"strong": "well outside the expert range",
              "notable": "outside the usual expert range"}
TIER_PCT = {"strong": "99%", "notable": "95%"}


def _ok(x: Any) -> bool:
    try:
        return x is not None and math.isfinite(float(x))
    except (TypeError, ValueError):
        return False


_NAMES = ("C", "C#", "D", "Eb", "E", "F", "F#", "G", "Ab", "A", "Bb", "B")


def pitch_name(midi: int | None) -> str:
    """Scientific pitch name of a MIDI note number (60 = C4); sharps / flats as usual."""
    if midi is None:
        return "?"
    m = int(midi)
    return f"{_NAMES[m % 12]}{m // 12 - 1}"


def _pct(x: float, nd: int = 0) -> str:
    return f"{100 * x:.{nd}f}%"


def _n(k: int, word: str, plural: str | None = None) -> str:
    return f"{k} {word if k == 1 else (plural or word + 's')}"


def _bars_list(rep: dict, idx: list[int]) -> str:
    labels = [rep["bars"][i]["label"] for i in idx]
    if not labels:
        return ""
    return ("bar " if len(labels) == 1 else "bars ") + ", ".join(labels)


def _span_mean(rep: dict, idx: list[int], ch: str, key: str) -> float:
    v = [rep["bars"][i][ch].get(key) for i in idx]
    v = [float(x) for x in v if _ok(x)]
    return float(np.mean(v)) if v else float("nan")


def _window_for(rep: dict, block: str, idx: list[int]) -> dict | None:
    wins = rep.get("interpretation", {}).get("windows", [])
    best = None
    for w in wins:
        if w["block"] == block and set(idx) & set(w["bars"]):
            if best is None or {"strong": 2, "notable": 1}.get(w["flat_tier"], 0) > \
                    {"strong": 2, "notable": 1}.get(best["flat_tier"], 0):
                best = w
    return best


# =========================================================================== header


def confidence_notes(rep: dict) -> list[str]:
    """Plain statements of what limits the confidence of this report."""
    out = []
    inp, refs, conf = rep["input"], rep["references"], rep["confidence"]
    prov = inp["provenance"]
    if conf["velocity"] == "low":
        if prov not in ("disklavier", "sensor"):
            why = f"the input is {prov} MIDI, not a direct key-sensor capture"
        else:
            why = ("the expert references for loudness are transcribed from audio (fewer than 8 "
                   "Disklavier or sensor recordings are available for this piece), and "
                   "transcription compresses loudness")
        out.append(f"Velocity (loudness) is low confidence: {why}. Loudness findings are shown "
                   "but are not used in \"What to practise\" (DECISIONS, after D-10).")
    if conf.get("transcribed"):
        lo, hi = cal.TRANSCRIBED_ERROR_RATE
        out.append(f"Transcribed input roughly doubles the apparent note-error rate "
                   f"({lo:.3f} to {hi:.3f} in D-10), so single flagged notes may be "
                   "transcription errors.")
    if conf.get("alignment_suspect"):
        mr = rep["correctness"].get("match_ratio")
        out.append(f"Only {_pct(mr)} of the notes could be matched to the score: the score may "
                   "not be the version that was played, so every finding is unreliable.")
    if not refs.get("tier_d_total"):
        out.append("No expert reference performances were available: tempo, loudness and timing "
                   "are shown without an expert comparison.")
    mf = refs.get("beat_map_mapped_fraction")
    if _ok(mf) and mf < 0.9:
        out.append(f"Only {_pct(mf)} of this score could be matched to the reference edition; "
                   "bars outside it have no expert band.")
    ec = rep["correctness"].get("expert_calibration", {})
    out.append(f"The note checker also flags notes in expert recordings: in a typical expert "
               f"performance {_pct(ec.get('share_bars_with_error_median', float('nan')))} of "
               "bars have at least one flagged note (real slips plus alignment noise). Only "
               "bars beyond what experts show are ranked.")
    out.append("Control measures (timing steadiness, evenness, pedal) describe this playing "
               "against experts; they are not yet validated as measures of skill (D-10).")
    return out


# =========================================================================== issues


def issue_text(item: dict, rep: dict) -> str:
    """One sentence per localized issue, grounded in the bar numbers."""
    idx, tier, ch, cat = item["bars"], item["tier"], item["channel"], item["category"]
    where = item["bars_label"].capitalize()
    range_w = TIER_WORDS.get(tier, "")
    bars = rep["bars"]
    if cat == "correctness":
        w = sum(bars[i]["correctness"]["n_wrong_pitch"] for i in idx)
        m = sum(bars[i]["correctness"]["n_missed"] for i in idx)
        e = sum(bars[i]["correctness"]["n_extra"] for i in idx)
        parts = [p for p in (_n(w, "wrong note") if w else "", _n(m, "missed note") if m else "",
                             _n(e, "extra note") if e else "") if p]
        this = "this bar" if len(idx) == 1 else "these bars"
        rec = [(bars[i]["label"], r) for i in idx for r in bars[i]["correctness"].get(
            "recurring", [])]
        if rec:
            nt = (rep.get("takes") or {}).get("n_takes", 0)
            what = "; ".join(f"bar {lab}: {r['text']} ({r['n_takes']} of {nt} takes)"
                             for lab, r in rec[:4])
            this_take = f" This take: {', '.join(parts)}." if parts else ""
            return (f"{where}: the same mistake recurs across your takes ({what}). A mistake "
                    f"repeated in several takes is learned, not a slip.{this_take} Relearn "
                    f"{this} slowly, hands separately, with the right notes.")
        return (f"{where}: {', '.join(parts)}; {range_w} for the note checker. Play {this} "
                "slowly, hands separately, until every note is secure.")
    if cat == "interpretation":
        dev = _span_mean(rep, idx, ch, "dev_mean")
        if ch == "tempo":
            if not _ok(dev):
                return f"{where}: your tempo shape is {range_w}."
            pc = math.exp(dev) - 1
            how = (f"you move ahead, about {_pct(abs(pc))} faster" if pc > 0
                   else f"you hold back, about {_pct(abs(pc))} slower")
            return (f"{where}: {how} than the typical expert shape (relative to your own "
                    f"average tempo); only {100 - int(TIER_PCT[tier][:-1])}% of experts depart "
                    "this far here. Check that this timing is what you intend.")
        if not _ok(dev):
            return f"{where}: your loudness shape is {range_w}."
        how = "louder" if dev > 0 else "softer"
        return (f"{where}: you play about {abs(dev):.0f} velocity units {how} than the typical "
                "expert shape (relative to your overall level); only "
                f"{100 - int(TIER_PCT[tier][:-1])}% of experts depart this far here.")
    if cat == "too_flat":
        w = _window_for(rep, ch, idx)
        what = "tempo" if ch == "tempo" else "loudness"
        if w and _ok(w.get("magnitude")) and _ok(w.get("magnitude_ref_median")):
            unit = "SD of log tempo" if ch == "tempo" else "SD in velocity units"
            fmt = ".3f" if ch == "tempo" else ".1f"
            nums = (f" ({unit} {w['magnitude']:{fmt}} vs expert median "
                    f"{w['magnitude_ref_median']:{fmt}})")
        else:
            nums = ""
        advice = ("Let the phrases breathe in time." if ch == "tempo"
                  else "Shape the phrases with more dynamic contour.")
        return (f"{where}: too flat. Your {what} varies less than {TIER_PCT[tier]} of experts "
                f"here{nums}. {advice}")
    if ch == "timing":
        ms = _span_mean(rep, idx, "timing", "noise_rms_ms")
        b = _span_mean(rep, idx, "timing", "noise_rms_beats")
        q = _span_mean(rep, idx, "timing", "ref_q95")
        qms = q * ms / b if _ok(ms) and _ok(b) and b > 0 and _ok(q) else float("nan")
        nums = f"{ms:.0f} ms RMS away from the expert timing pattern" if _ok(ms) else \
            "far from the expert timing pattern"
        lim = f", while 95% of experts stay within {qms:.0f} ms here" if _ok(qms) else ""
        return (f"{where}: note timing is less steady than experts ({nums}{lim}). Practise "
                "with a slow, steady inner pulse.")
    if ch == "pedal":
        nch = sum(bars[i]["pedal"]["n_harmony_changes"] for i in idx)
        blur = sum(bars[i]["pedal"]["blur_fraction"] * bars[i]["pedal"]["n_harmony_changes"]
                   for i in idx if _ok(bars[i]["pedal"]["blur_fraction"]))
        return (f"{where}: the pedal is held through {round(blur)} of {nch} harmony changes; "
                "experts on this score change the pedal there. Lift just after each new "
                "harmony.")
    if ch == "evenness":
        cv = _span_mean(rep, idx, "evenness", "ioi_cv")
        q = _span_mean(rep, idx, "evenness", "ref_q95")
        return (f"{where}: the running notes are uneven (timing variation {cv:.3f} of the "
                f"note length, 95% of experts on this passage stay below {q:.3f}). Practise "
                "the run slowly with even, light fingers.")
    return f"{where}: {range_w}."


# =========================================================================== summary cards


def _correctness_card(rep: dict) -> dict:
    c = rep["correctness"]
    ec = c.get("expert_calibration", {})
    graded = c["n_score_notes"] - c.get("n_interpolated", 0)
    f = [f"{c['n_correct']} of {graded} score notes were played as written "
         f"({_pct(c['accuracy'], 1)}).",
         f"Flagged: {_n(c['n_wrong_pitch'], 'wrong note')}, {_n(c['n_missed'], 'missed note')} "
         f"and {_n(c['n_extra'], 'extra note')}, in {c['n_bars_with_errors']} of "
         f"{c['n_bars']} bars."]
    er = c.get("error_rate")
    if _ok(er):
        s = (f"Error rate {_pct(er, 1)}. On expert recordings this checker reports a median of "
             f"{_pct(ec['error_rate_q50'], 1)} (95% of experts below "
             f"{_pct(ec['error_rate_q95'], 1)}).")
        t = c.get("error_rate_tier", "none")
        if t != "none":
            s += f" Yours is higher than {TIER_PCT[t]} of expert performances."
        f.append(s)
    worst = sorted(rep["bars"], key=lambda b: -b["correctness"]["n_errors"])[:3]
    worst = [b for b in worst if b["correctness"]["n_errors"] > 0]
    if worst:
        f.append("Most flagged notes: " + ", ".join(
            f"bar {b['label']} ({b['correctness']['n_errors']})" for b in worst) + ".")
    ns, nn = c.get("n_bars_strong", 0), c.get("n_bars_notable", 0)
    f.append(f"Bars beyond the expert range: {ns} strong, {nn} notable (missed notes are "
             "judged per bar, not per note).")
    tk = rep.get("takes")
    if tk and tk.get("takes"):
        rec = tk["recurring_error_bars"]
        s = (f"Across {tk['n_takes']} takes, the same wrong note recurs in "
             + (_n(len(rec), "bar") + ": " + ", ".join(rec[:12]) if rec else "no bar") + ".")
        if tk.get("promoted"):
            s += (f" Checked against {tk['n_expert_checks']} expert recordings of this score, "
                  "so checker artefacts are removed." + (
                      " A mistake repeated across takes is learned, not a slip, so these bars "
                      "are marked strong." if rec else ""))
        elif rec:
            s += (" Fewer than two expert recordings of this score were available to rule out "
                  "checker artefacts, so these bars are not marked strong.")
        f.append(s)
    return {"title": "Correctness", "findings": f}


def _control_card(rep: dict) -> dict:
    f = []
    t, c = rep.get("timing") or {}, rep["control"]
    if _ok(t.get("noise_rms_ms")):
        nt = sum(1 for b in rep["bars"] if b["timing"]["tier"] != "none")
        ns = sum(1 for b in rep["bars"] if b["timing"]["tier"] == "strong")
        f.append(f"Timing steadiness: your note timing departs from the expert timing pattern "
                 f"by {t['noise_rms_ms']:.0f} ms RMS ({t['noise_rms_beats']:.3f} beats), "
                 f"against {t.get('n_references', 0)} reference performances; "
                 f"{nt} bars are outside the expert range ({ns} strongly).")
    elif _ok(c.get("jitter_nometric_rms_ms")):
        f.append(f"Timing steadiness (no references): {c['jitter_nometric_rms_ms']:.0f} ms RMS "
                 "after removing your own recurring within-bar pattern.")
    if c.get("even_strict_n_runs"):
        runs = [r for r in rep.get("evenness_runs", []) if _ok(r.get("ioi_cv"))]
        s = (f"Evenness in {_n(int(c['even_strict_n_runs']), 'scale or figure passage')}: "
             f"timing varies by {c['even_strict_ioi_cv']:.2f} of the note length (CV) at "
             f"{c['even_strict_note_rate_nps']:.1f} notes per second; loudness by "
             f"{c['even_strict_vel_sd_midi']:.1f} velocity units (SD).")
        near = sorted({lab for r in runs for lab in r.get("literature_similar_rate", [])})
        rates = [e["note_rate_nps"] for e in cal.LITERATURE_EVENNESS]
        if near:
            ents = [e for e in cal.LITERATURE_EVENNESS if e["label"] in near]
            nr = sum(1 for r in runs if r.get("literature_similar_rate"))
            s += (f" {_n(nr, 'passage')} run at a speed where published values exist: "
                  + "; ".join(f"{e['label'].lower()} at {e['note_rate_nps']} notes per second, "
                              f"CV about {e['ioi_cv_lo']:.2f}"
                              + (f"-{e['ioi_cv_hi']:.2f}" if e["ioi_cv_hi"] != e["ioi_cv_lo"]
                                 else "") + f" ({e['source']})" for e in ents)
                  + ". These come from instructed scales, so they are a floor, not a norm.")
        else:
            s += (f" Published values come from instructed scales at {min(rates):.1f} to "
                  f"{max(rates):.1f} notes per second, so none is at your note rate; unevenness "
                  "rises with speed, so they are not compared here.")
        lo, hi = cal.VELOCITY_JND_MIDI
        s += f" For scale, listeners notice loudness steps of about {lo} to {hi} velocity units."
        f.append(s)
    if _ok(c.get("hand_async_median_ms")):
        m = c["hand_async_median_ms"]
        side = "left hand" if m > 0 else "right hand"
        f.append(f"Hands together: at shared onsets the {side} typically sounds first, by "
                 f"{abs(m):.0f} ms (median); after allowing for the louder hand sounding "
                 f"earlier, the spread is {c['hand_async_resid_sd_ms']:.0f} ms (SD). "
                 "Asynchronies within about 30 ms are hard to hear (Goebl et al. 2009).")
    if c.get("pedal_available") and _ok(c.get("pedal_blur_fraction")):
        s = (f"Pedal: held through {_pct(c['pedal_blur_fraction'])} of "
             f"{int(c['n_harmony_changes'])} detected harmony changes (detector F1 0.76 against "
             "annotated harmony).")
        if not c.get("n_pedal_references"):
            s += " No expert pedal data exist for this score, so this is not compared."
        f.append(s)
    elif not c.get("pedal_available"):
        f.append("Pedal: no pedal data in this file.")
    return {"title": "Control", "findings": f}


def _shaping_card(rep: dict) -> dict:
    s = rep.get("shaping") or {}
    f = []
    for ch, what in (("velocity", "loudness"), ("articulation", "note lengths")):
        c = s.get(f"coherence_{ch}")
        if c and c.get("defined") and _ok(c.get("r2_no_markings")):
            r2 = c["r2_no_markings"]
            f.append(f"Structure in {what}: {_pct(max(r2, 0))} of the note-to-note variation "
                     f"is predictable from pitch, harmony, metre and phrase position in held-out "
                     f"bars (R² {r2:.2f}, dynamic markings left out).")
        elif c:
            f.append(f"Structure in {what}: not reported (too few bars for the check).")
    p = s.get("phrase_tempo")
    if p and _ok(p.get("concave_share")):
        f.append(f"Phrases in time: {_pct(p['concave_share'])} of "
                 f"{int(p.get('n_phrases', 0))} phrases (boundaries found from cadences) slow "
                 f"at both ends; with the boundaries shifted by 2 bars the share is "
                 f"{_pct(p['null_concave_share'])}, so the excess is "
                 f"{100 * p['concave_excess']:+.0f} points.")
    v = s.get("voicing")
    if v and _ok(v.get("vel_diff_mean_midi")):
        lead = v.get("lead_mean_ms")
        r = v.get("lead_vel_corr")
        f.append(f"Melody over accompaniment: the melody is louder at "
                 f"{_pct(v['frac_melody_louder'])} of shared onsets, by "
                 f"{v['vel_diff_mean_midi']:.1f} velocity units on average"
                 + (f", and sounds {abs(lead):.0f} ms {'early' if lead > 0 else 'late'}"
                    if _ok(lead) else "")
                 + (f" (timing and loudness difference correlate, r = {r:.2f})" if _ok(r) else "")
                 + ".")
    d = s.get("dynamics")
    if d and _ok(d.get("hairpin_agree_frac")):
        f.append(f"Written dynamics: {_pct(d['hairpin_agree_frac'])} of "
                 f"{int(d.get('hairpin_n', 0))} hairpins go the marked way"
                 + (f"; {_pct(d['level_agree_frac'])} of {int(d.get('level_n', 0))} level "
                    "changes (p, f, ...)" if _ok(d.get("level_agree_frac")) else "") + ".")
    f.append("Tempo coherence with the phrase structure is not reported: it needs annotated "
             "phrase boundaries (F-05b).")
    return {"title": "Shaping", "findings": f}


def _interp_card(rep: dict) -> dict:
    it = rep.get("interpretation") or {}
    f = []
    if not it:
        return {"title": "Interpretation", "findings": [
            "No expert comparison: no reference performances of this piece."]}
    to = it.get("tempo_overall", {})
    if _ok(to.get("ref_median")):
        f.append(f"Overall tempo over the bars you played: {to['target_bpm']:.0f} beats per "
                 f"minute; over the same bars the {to['n_refs']} reference performances run "
                 f"from {to['ref_q10']:.0f} to "
                 f"{to['ref_q90']:.0f} (10th to 90th percentile, median "
                 f"{to['ref_median']:.0f}). You are faster than {_pct(to['pct_refs_slower'])} "
                 "of them.")
    for ch, what in (("tempo", "Tempo shape"), ("velocity", "Loudness shape")):
        ns = sum(1 for b in rep["bars"] if b[ch]["tier"] == "strong")
        nn = sum(1 for b in rep["bars"] if b[ch]["tier"] == "notable")
        wins = [w for w in it.get("windows", []) if w["block"] == ch and w["status"] == "ok"]
        s = (f"{what}: {ns} bars strongly and {nn} notably outside the expert range "
             f"(out of {len(rep['bars'])}).")
        typ = [w for w in wins if _ok(w.get("typicality_pct"))]
        if typ:
            w = min(typ, key=lambda w: w["typicality_pct"])
            lab = _bars_list(rep, [w["bars"][0], w["bars"][-1]]).replace(", ", "-")
            s += (f" Least typical section: {lab}, where {_pct(w['typicality_pct'])} of "
                  "held-out experts are at least as unusual.")
        flat = [w for w in wins if w["flat_tier"] != "none"]
        ext = [w for w in wins if w["extreme_tier"] != "none"]
        if flat:
            s += f" Too flat in {_n(len(flat), 'section')}."
        if ext:
            s += f" More extreme than 95% of experts in {_n(len(ext), 'section')}."
        if ch == "velocity" and rep["confidence"]["velocity"] == "low":
            s += " (Low confidence, see the notes above.)"
        f.append(s)
    f.append("Individual choices outside the shared expert pattern are normal: experts share "
             "only a small part of their shaping (R-02). A flag says \"unusual here\", not "
             "\"wrong\".")
    f.append("Model-based quality ratings are not included: the rating model is still at "
             "single-rater reliability (R-04).")
    return {"title": "Interpretation", "findings": f}


def summary_findings(rep: dict) -> list[dict]:
    """The four summary cards, in report order. No overall grade."""
    return [_correctness_card(rep), _control_card(rep), _shaping_card(rep), _interp_card(rep)]
